const items = [
    {
        id: 1,
        title: 'mug 1',
        category: 'mugs',
        price: 15.99,
        img: './images/mug.jpg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 2,
        title: 'mug 2',
        category: 'mugs',
        price: 15.99,
        img: './images/mug.jpg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },

      {
        id: 3,
        title: 'mug 3',
        category: 'mugs',
        price: 15.99,
        img: './images/mug.jpg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 4,
        title: 'illustration 1',
        category: 'illustrations',
        price: 15.99,
        img: './images/item-1.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 5,
        title: 'illustration 2',
        category: 'illustrations',
        price: 15.99,
        img: './images/item-1.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 6,
        title: 'calendar 1',
        category: 'calendars',
        price: 15.99,
        img: './images/item-1.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 7,
        title: 'calendar 2',
        category: 'calendars',
        price: 15.99,
        img: '',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 8,
        title: 'set stickers 1',
        category: 'stickers',
        price: 15.99,
        img: './images/stickers.jpg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      }, 
      {
        id: 9,
        title: 'set stickers 2',
        category: 'stickers',
        price: 15.99,
        img: './images/item-1.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      }, 
      {
        id: 10,
        title: 'set stickers 3',
        category: 'stickers',
        price: 15.99,
        img: './images/item-1.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
]

export default items; 