

const items = [
    {
        id: 1,
        title: 'mug one',
        category: 'mugs',
        price: 15.99,
        img: 'https://cdn.connox.fr/m/100030/223280/media/eva-solo/Nordic-Kitchen/Tasse/Eva-Solo-Nordic-Kitchen-Tasse-30-cl-schwarz-Freisteller.jpg',
        desc: `Je suis une tasse`,
      },
      {
        id: 2,
        title: 'mug two',
        category: 'mugs',
        price: 15.99,
        img: 'https://cdn.connox.fr/m/100030/223280/media/eva-solo/Nordic-Kitchen/Tasse/Eva-Solo-Nordic-Kitchen-Tasse-30-cl-schwarz-Freisteller.jpg',
        desc: `Je suis une tasse`,
      },

      {
        id: 3,
        title: 'mug three',
        category: 'mugs',
        price: 15.99,
        img: 'https://cdn.connox.fr/m/100030/223280/media/eva-solo/Nordic-Kitchen/Tasse/Eva-Solo-Nordic-Kitchen-Tasse-30-cl-schwarz-Freisteller.jpg',
        desc: `Je suis une tasse`,
      },
      {
        id: 4,
        title: 'illu one',
        category: 'illustrations',
        price: 15.99,
        img: 'https://secure.img1-fg.wfcdn.com/im/34055319/resize-h755-w755%5Ecompr-r85/1202/120254893/%27Music+Notes+White+Background%27+by+Rachel+Lee+-+Floater+Frame+Painting+Print+on+Canvas.jpg',
        desc: `Je suis une illustration`,
      },
      {
        id: 5,
        title: 'illu two',
        category: 'illustrations',
        price: 15.99,
        img: 'https://secure.img1-fg.wfcdn.com/im/34055319/resize-h755-w755%5Ecompr-r85/1202/120254893/%27Music+Notes+White+Background%27+by+Rachel+Lee+-+Floater+Frame+Painting+Print+on+Canvas.jpg',
        desc: `Je suis une illustration`,
      },
      {
        id: 6,
        title: 'illu three',
        category: 'illustrations',
        price: 15.99,
        img: 'https://secure.img1-fg.wfcdn.com/im/34055319/resize-h755-w755%5Ecompr-r85/1202/120254893/%27Music+Notes+White+Background%27+by+Rachel+Lee+-+Floater+Frame+Painting+Print+on+Canvas.jpg',
        desc: `Je suis une illustration`,
      },
      {
        id: 7,
        title: 'calendar one',
        category: 'calendars',
        price: 15.99,
        img: 'https://i.pinimg.com/originals/05/e9/85/05e985150b50e41240c9abf8c2abffd0.jpg',
        desc: `Je suis un calendrier`,
      },
      {
        id: 8,
        title: 'calendar two',
        category: 'calendars',
        price: 15.99,
        img: 'https://i.pinimg.com/originals/05/e9/85/05e985150b50e41240c9abf8c2abffd0.jpg',
        desc: `Je suis un calendrier`,
      },
      {
        id: 9,
        title: 'calendar three',
        category: 'calendars',
        price: 15.99,
        img: 'https://i.pinimg.com/originals/05/e9/85/05e985150b50e41240c9abf8c2abffd0.jpg',
        desc: `Je suis un calendrier`,
      },
      {
        id: 10,
        title: 'stickers one',
        category: 'stickers',
        price: 15.99,
        img: 'https://img.freepik.com/free-vector/black-white-circle-t-shirt-sticker-design_24992-312.jpg',
        desc: `Je suis un set de sticker`,
      }, 
      {
        id: 11,
        title: 'stickers two',
        category: 'stickers',
        price: 15.99,
        img: 'https://img.freepik.com/free-vector/black-white-circle-t-shirt-sticker-design_24992-312.jpg',
        desc: `Je suis un set de sticker`,
      }, 
      {
        id: 12,
        title: 'stickers three',
        category: 'stickers',
        price: 15.99,
        img: 'https://img.freepik.com/free-vector/black-white-circle-t-shirt-sticker-design_24992-312.jpg',
        desc: `Je suis un set de sticker`,
      },
]

export default items; 